language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: shareyourideas-nodejs-jpo
  api_key:
    secure: YVqb16iHovhsdWFvsUNfuPKAPLwDmSVZYKXQiqgKqrxKPTheIjlUHj1mbGhCQHdeu/mAhe7Zlsb7RHr7X/mct6275fsK1VJRewsbHAI9Wyls14Gh4hYd+jzqdH/7fOGtXXnB6aaWNGngWM32pwJed5Ht36Z1gtVSCbKLL6gN/NtA8c04/Xpik39wBTH4GY+lbrblkhjxDKXGVUjwtCy3eOF1afjzeaV30ogNlC/5FWfaeYIdMJeHkwbXpkXJtqaaJjwDEPYcfLIgmiQdr5Y5ivsvKHhZ6WDIAFlWBm3uPj9hWc1XShigcfXp7XBgp/NhjK5cTF2yzMsMiImLHIYnZwTPOQqIQ6BDEtiDb1ELAKviy2eDENnK05v+tJ5qVmkt65lnnaH1zGeF4XvTn8uwgJu0pOtwUNSdZP5Unu4BDult30LHZWNuM3rFvEXWE54+uGff+J1W1PaCal/x5bgCMNrYkiRaQeEg/7rn18hrJLVFLIOx1dTJD2iohn+BPELla12IzwHfvJoQeF0n9sDlk3CInenaw+iblReG8szjxOnFCKTt3G95+8Put9O8VB6Y3qZuZAheMdvWwr+ya21lVSMIYLW2gVci9rz3cw6GMxjbocSmzylmnUy1mRmOrFxkm1ydU3JUvhEobhIDp81M86nBSv3ph/DUKy3DCrFuFQg=
