version: "3"
services: 
  api:
    build: .
    depends_on: 
      - mongo
    environment: 
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/test
      - APPLICATION_NAME="Share Your Idea"
      - JWT_SECRET=admpodfsdkmasdsñlmlsmslmscslcslcms
      - CACHE_KEY=Wasd@1234
      - SWAGGER_DOC=swaggerPROD
    ports: 
      - "5000:5000"

  mongo:
    image: mongo